// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvjkfuhsvyljcttdvhql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2amtmdWhzdnlsamN0dGR2aHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjM0ODIsImV4cCI6MjA2NDU5OTQ4Mn0.n1l6xiR3ugOSMGR4c1VQ1xQNl0kRms7fqfOwvIPDYOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);